Fix a loads of "Undefined reference to" errors because IncommingRunnerModel would return an invalid variant if the lap was invalid
This happen when the SI number was unknown to the mapper.